apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-server-egress
  namespace: server
spec:
  podSelector:
    matchLabels:
      app: server
  policyTypes:
    - Egress
  egress: []